server:
  port: 8280
  servlet:
    context-path: /business

banban:
  token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpblR5cGUiOiJzdHVkZW50IiwiZXhwIjoxNjA4NTgyNjAwLCJ1c2VySWQiOiIyMDIwMTAxMjIzMTYyMGR6NnB3cmVvd2Qzc3J0cjdlbWRleTQiLCJpYXQiOjE2MDYwMDQ4MTcsImp0aSI6IjkyZWE3ZmUyZWJiMTRmYTQ5ZmI3MTZlZmNmNWQ2NzhmIn0.Yyzv88C6BWSQpuXeORdbMITEfxGCc5laUeazrzXpuVs

ticket:
  banban:
    special:
      inculde:
        #格式为日期与时间一一对应，逗号分隔
        day:
        time:
      exclude:
        day: 11-21
        time: 08:00-13:00
    daily:
      common:
        duration: 1,1,1,2,2,3
        period: 3
        start-time: 08:30:00
        weekday:
          start-time: 18:00
    schedule:
      query-date: 2020-11-17
      common:
        after: 2
        begin-time: 08:25
        start-time: 08:00
        weekday:
          start-time: 18:00


httpclient:
  # 最大连接数
  maxtotal: 64
  # 每个route默认的最大连接数
  defaultMaxPerRoute: 64
  # 连接上服务器(握手成功)的时间，超出抛出connect timeout
  connectTimeout: 10000
  # 从连接池中获取连接的超时时间，超时间未拿到可用连接，会抛出org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
  connectionRequestTimeout: 10000
  # 服务器返回数据(response)的时间，超过抛出read timeout
  socketTimeout: 10000
  # 存活时间
  validateAfterInactivity: 10000



